### ISSUE TITLE
[Bug]: Synchronization error (password_not_matched)

### ISSUE THREAD

**Issue by varrcan** [sboesen/remotely-secure#20]
### What happened?

Hello! At the first synchronization, the files are successfully saved to S3 storage.
But if I press the sync button again, the error "password_not_matched" occurs.

At the same time, the connection check is successful in the settings.
Maybe I'm doing something wrong?

![img1611202370d0](https://github.com/sboesen/remotely-secure/assets/23196073/36841920-f77d-4386-bdc9-0a239201bd59)

![img161120239bca](https://github.com/sboesen/remotely-secure/assets/23196073/c04fe754-301b-4661-8608-8c3d736a9267)

### What OS are you using?

Linux, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.4.10

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hello, sorry it isn't working there - are you confident the password is the same on both devices? (I'm assuming the error is syncing between two devices because you checked Linux + Android, let me know if that's not the case).

Will give it a test again on Linux more tomorrow just to make sure it's not an issue specific to how it's running on Linux.

**Comment by varrcan** [comment]
I marked Android because it has exactly the same error and behavior.
If there are no files in the S3 package, then synchronization is successful. But if you click the icon again, an error occurs.

I checked the password, it's exactly correct. Moreover, there are no errors when checking the connection from the settings.


![photo_2023-11-16_13-25-05](https://github.com/sboesen/remotely-secure/assets/23196073/bc6bb75e-6b47-4f1b-ad22-bd8f34113717)
![photo_2023-11-16_13-24-42](https://github.com/sboesen/remotely-secure/assets/23196073/0c0aca47-24cf-477f-a712-8f32592077e9)

**Comment by varrcan** [comment]
Here is such a log at the first synchronization, when there are no files in the bucket yet. Everything goes well, the files are uploaded. If you click the sync icon again, an error occurs.


![img16112023111d](https://github.com/sboesen/remotely-secure/assets/23196073/6361b0f5-789e-4f71-97d4-ceccec357573)

**Comment by sboesen** [comment]
Got it, thanks for clarifying. Something is definitely going on - my testing on Android has been limited as well, but I'll do some investigating to see if I can reproduce this issue on my end. Thanks for opening the bug report!

**Comment by varrcan** [comment]
If you need any help in testing from my side, please let me know.

You have created a very cool plugin, it would be great if it worked for me)

**Comment by lvr83** [comment]
I can confirm the behaviour for sync without E2E passwort:
I use Linux and Android and try to sync via webdav to a nextcloud server.
When setting up a new vault under Linux and sync it for the first time no error occurs. When syncing the second time from Linux I'll get the error "password not matched". Same when trying to sync the once synced version from nextcloud to android.

After changing the options and using a password for E2E it runs without error from both sides.

Hope this helps! Great Tool!

**Comment by sboesen** [comment]
Ooooo, I somehow missed this is *without* any password set. That helps narrow it down, thanks!

**Comment by varrcan** [comment]
I confirm that everything worked when setting the E2E password, the files are synchronized normally in S3!

**Comment by sboesen** [comment]
This one should also be fixed in 0.4.12, please reopen if it still errors without a password for you.

**Comment by varrcan** [comment]
Updated to version 0.4.12, deleted the cache, deleted all files in S3 storage. 

Unfortunately, the error is still being reproduced. The first synchronization is successful, then with an error.

![img1711202392c5](https://github.com/sboesen/remotely-secure/assets/23196073/a1394848-1dd2-436a-bc0b-329a59a5ee96)

**Comment by sboesen** [comment]
Sorry about that! I tested if a few times but was able to reproduce that issue. I assumed the order of objects returned was deterministic but it wasn't. This should work consistently now (in 0.4.13). Let me know if it still doesn't work for you, thanks!

**Comment by varrcan** [comment]
Unfortunately, it still doesn't work. The error is the same, on the same line.

**Comment by sboesen** [comment]
I'm not sure why this is happening, but I added a debug log message to try and narrow this down. Please try the latest version and open settings -> remotely secure -> set enable debug info from "false" to "true" and check the console logs again. Sorry this keeps happening!

For what it's worth I haven't been able to reproduce the issue anymore, but will keep investigating.

**Comment by varrcan** [comment]
```log
password is blank?  true  remote has metadata?  false
```


![img171120238829](https://github.com/sboesen/remotely-secure/assets/23196073/687edb48-59cd-419b-80f5-303a8e2f1369)

**Comment by varrcan** [comment]
If you delete all the files in S3 storage and start synchronization again, then the log shows (and then successful synchronization is performed):

```log
no metadata file, so no fetch
```

I don't know how important the log is at the first successful synchronization.

![img1711202312ad](https://github.com/sboesen/remotely-secure/assets/23196073/52cd1768-7daa-413e-aa3f-0b86efc86d9b)

**Comment by sboesen** [comment]
Hmm, but it looks like you're uploading a file so there should be a metadata file. Maybe not. Need to investigate how / why those file(s) are created - this is definitely bizarre. May take a minute to fix this.

Until I can get a permanent fix highly recommend setting a placeholder password and then migrating to no password when it's fixed.

Also wanted to call out it's not end-to-end encrypted without a password if that matters to you.

**Comment by varrcan** [comment]
I have very few files, it's more like a test storage. Encryption is not so important.

**Comment by sboesen** [comment]
This should be fixed in 0.4.15 as I now upload the metadata file unconditionally. Was able to reproduce the issue and this fixed it for me - please let me know if it continues happening, sorry again for the back & forth!

**Comment by varrcan** [comment]
syncing worked fine, thank you!

**Comment by sboesen** [comment]
Glad to hear & no problem! It is very slightly inefficient until you delete a minimum of one file now, but hard to fix this without refactoring a bunch of the sync code.

**Comment by ProgramerLiang** [comment]
I used WebDAV (with password but no e2e-encryption) trying to sync, but got the same problem. ):
I created a completely new folder but nothing better.
This plugin is very good. I've used it for a time, but it went wrong since updated to some specific version.
Hope to hear any respond!

<img width="327" height="1039" alt="Image" src="https://github.com/user-attachments/assets/2f722f5d-0e78-4bdf-9da9-c45c06005c49" />
